const GLOBAL_ACTIONS = {
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_TOKEN: "SET_TOKEN",
  SET_USERNAME: "SET_USERNAME",
  SET_SENTIMENT: "SET_SENTIMENT",
  SET_TOPICS: "SET_TOPICS",
  SET_IS_ANALYSIS_LOADING: "SET_IS_ANALYSIS_LOADING",
  SET_QUESTION: "SET_QUESTION",
  SET_AUDIO_URL: "SET_AUDIO_URL",
};

export default GLOBAL_ACTIONS;
